services:
  regexr:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - phpapi
  phpapi:
    build:
      dockerfile: server/Dockerfile
      context: .
    ports:
      - "9000:80"
